### ISSUE TITLE
Warning on points not being in plane. 

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JuliaGeometry/DelaunayTriangulation.jl#208]
With the Comodo integration/use of your package, I am currently getting this warning: 
```
┌ Warning: The provided points are not in the plane. All but the first two coordinates of each point will be ignored.
└ @ DelaunayTriangulation ~/.julia/packages/DelaunayTriangulation/74rOt/src/algorithms/triangulation/check_args.jl:114
```

This is because the Delaunay triangulations occur of course in 3D. However, all point sets and treatments of them in Comodo are always 3D. If Delaunay triangulation is used then it is always for planar point sets where the 3rd coordinate can safely be ignored. Hence I was wondering, since I keep getting this warning, if this warning is actually needed/relevant. Folks probably should know your package does the 2D Delaunay triangulation and ignores the 3rd dimension. So perhaps a statement on the documentation saying that any higher dimensions are ignored, would be good/sufficient, instead of the warning?

**Comment by DanielVandH** [comment]
This was added in response to the issue https://github.com/JuliaGeometry/DelaunayTriangulation.jl/issues/177 where a user did think that 3D might work. It should only be showing once, right? Is it showing more than once?

**Comment by Kevin-Mattheus-Moerman** [comment]
Yes, I think it occurs once. 

I have no strong feelings either way. I think a statement like that is fine.

**Comment by DanielVandH** [comment]
The main reason I decided with the warning over just re-emphasising it was because it might not be immediately obvious to new users that the coordinates are being ignored, since it's just being ignored silently. Sometimes things just silently working / not working can be a bit confusing for new users I think. 

If you think it becomes a bit too annoying there might be a better compromise somewhere.
